export const GET_MAIN_PAGE_DATA = "GET_MAIN_PAGE_DATA";

export const GET_ALL_CLASSES = "GET_ALL_CLASSES";
export const ADD_CLASS = "ADD_CLASS";
export const UPDATE_CLASS = "UPDATE_CLASS";
export const DELETE_CLASS = "DELETE_CLASS";

export const GET_ALL_TEACHERS = "GET_ALL_TEACHERS";
export const ADD_TEACHERS = "ADD_TEACHERS";
export const UPDATE_TEACHERS = "UPDATE_TEACHERS";
export const DELETE_TEACHERS = "DELETE_TEACHERS";

export const GET_ALL_SUBJECTS = "GET_ALL_SUBJECTS";
export const ADD_SUBJECTS = "ADD_SUBJECTS";
export const UPDATE_SUBJECT = "UPDATE_SUBJECT";
export const DELETE_SUBJECT = "DELETE_SUBJECT";
